### ISSUE TITLE
Include number of new notifications beside bell

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#137]

**Comment by 2qx** [comment]
This is closed out here:

https://github.com/FreeTrade/memberdev/commit/b45a0a0d48ebfc77955944345f4cc456542d217d

and working in dev.  

It might be nice to put the count in a large badge:

![image](https://user-images.githubusercontent.com/57997077/71768765-6c72b000-2ee7-11ea-88ad-5cd117312a8f.png)
