### ISSUE TITLE
help the project

### ISSUE THREAD

**Issue by ForgeableSum** [memberapp/memberapp.github.io#23]
I like the project and would like to contribute. I noticed a major bug in which the roottxid comes in empty from the JSON handled with the XHR request. It makes some of the links go to empty pages. 

Problem is I don't have the server implementation at memberjs.org to properly debug this. Who controls memberjs.org and where can I get the codebase for that?

Thanks!

**Comment by FreeTrade** [comment]
The backend is a bit of a mess and I haven't open sourced it yet.

**Comment by ForgeableSum** [comment]
I take it it's php and some database software like mongo or mysql? If you include it in the repo i can help fix problems. It appears the project hasn't been worked on in 10 months.

**Comment by FreeTrade** [comment]
This is fixed now, Member just needs either a root or a post id to display the thread.
