### ISSUE TITLE
Localization fails when loading from local file system

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#256]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///C:/locale/en.json. (Reason: CORS request not http).

TypeError: NetworkError when attempting to fetch resource.

@2qx

**Comment by 2qx** [comment]
The site should still work even if the translation file is not loaded. 

To get around browser ssl restrictions for notification testing, I configured a node express server and ssl on a local address.  It is a bit involved. 

0. Create a .local entry in my local hosts file (i.e. member.local) 
1. Create an SSL Authority certificate
2. Create an SSL Certificate and signing request
3. Sign the ssl certificate with the authority 
4. Trust the SSL Authority in the browsers I wish to test in,
5. Reroute traffic bound for port 443 to my development port.

I have an readme, but it is just a guide for linux. 

I can investigate if there is a flag in chrome, but it doesn't seem like something that should be left on.  

However, I think the best solution might be to change the way the localization files are loaded so they it doesn't hit security constraints.

**Comment by FreeTrade** [comment]
For the localization files - I agree, best solution is to change the way they are loaded. Should be possible to load them in a way that security policy doesn't object to.

For the notifications - are you saying that the notification service has got to be on the same domain as the index.html? This would necessitate moving to a new domain, which i've resisted until now, but it's probably worth it for notifications, which I agree are necessary to create engagement.

**Comment by 2qx** [comment]
So I tested using just a couple static serving utilitys. Neither chrome nor firefox objected if it was served from localhost and everything worked without SSL. Both the language files and service worker etc worked without issue. 

It's much much easier than configuring full SSL for a dev environment.  

Documentation for using npm or python modules has been added in the getting started section of the readme.  

Does that work?

**Comment by FreeTrade** [comment]
I'm not familiar with static serving utilities but I was hoping that user could just download the files, unzip and run Member direct from the file system without need for any additional install - is that where we'll end up?

For the notifications, if we can use different domains, then we could test the notifications against a live server?

**Comment by FreeTrade** [comment]
On the dev version, loading direct from filesystem, getting '%s hours' instead of times - I guess vavilon is not replacing or erroring out to the correct value.

**Comment by FreeTrade** [comment]
Perhaps if the localization files used a .js format, it would be possible to load them dynamically from the filesystem. Pretty sure there is a way to dynamically load .js even if it is a filesystem protocol.
