### ISSUE TITLE
how do i withdraw my bitcoin cash if i need to

### ISSUE THREAD

**Issue by marlon99rocks** [memberapp/memberapp.github.io#273]
how do i withdraw my bitcoin cash if i need to

**Comment by 2qx** [comment]
You should be able to copy your private key from the settings page.  The secret controls your bitcoin cash. 

You should be able import the private key into a wallet like Electron-cash and send it anywhere from there.  

See also #220

**Comment by marlon99rocks** [comment]
thanks
