### ISSUE TITLE
i just lost all my bitcoin cash this morning just wondering why

### ISSUE THREAD

**Issue by marlon99rocks** [memberapp/memberapp.github.io#274]
im lost

**Comment by 2qx** [comment]
Was your private key an uncompressed private key (a long string of random numbers) or a 12 word seed phrase?

**Comment by marlon99rocks** [comment]
it was a comment i did https://blockchair.com/bitcoin-cash/address/qpwvatqew42eg6xe2fejzlwnllq7755m8sp4ztzaz8

**Comment by marlon99rocks** [comment]
is it safe the website because it took all my money when i comment

**Comment by 2qx** [comment]
It appears that shortly after asking how to withdraw funds, funds where transferred from the above address in this transaction: 

77ed11a2ba4aa4ba7c0e30cb00ac9d664df860e7eac49cbc9b1283db3a1be0c8

**Comment by marlon99rocks** [comment]
so did i lost that 45 cents how

**Comment by marlon99rocks** [comment]
and i tanfur that to my other wallet that 1 cents

**Comment by marlon99rocks** [comment]
can you tell me where that 45 cents when on here https://blockchair.com/bitcoin-cash/address/qpwvatqew42eg6xe2fejzlwnllq7755m8sp4ztzaz8

**Comment by marlon99rocks** [comment]
i guess i got money
https://blockchair.com/bitcoin-cash/transaction/be843f13dab28ebb47a6f214a456ea201588d6cd169a271cbdf32813379d58d3
