### ISSUE TITLE
markdown editor is duplicated sometimes

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#280]

**Comment by 2qx** [comment]
FYI. The experience on android is horrific. As soon as the user starts typing, it turns into gibberish.

I took home a USB-B to USB-C cable to debug this, if I get time.  But I would like to wrap up the Map PR, and fix the CSP for translations.

**Comment by FreeTrade** [comment]
The markdown editor should already be removed on android completely.

We really need to change it to the tip tap editor - that's the one used by read.cash.

**Comment by FreeTrade** [comment]
couldn't reproduce
