### ISSUE TITLE
Clicking back should bring you back to the same scroll position

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#292]
request from zquestz

Also, big feature request. When I click on an article and it goes to the show page, how can I go back to the last page I was on without starting at the top?
I need index -> show -> index at position I clicked show =)

**Comment by FreeTrade** [comment]
Some browsers seem to have some capacity to do this automatically, but for full support, this may require recording scroll position with back history in utils.

**Comment by Real-FEELS** [comment]
+1
