### ISSUE TITLE
Bug: geohash of map input is throwing points to 180 meridian

### ISSUE THREAD

**Issue by 2qx** [memberapp/memberapp.github.io#302]
Users in the eastern hemisphere are having map input thrown to the 180 meridian because the continuous tiling is allowing them to input points beyond what the geohash function can receive.

Perhaps clipping:
https://github.com/aparshin/leaflet-boundary-canvas

Or updating the geohash function is the solution.
![member_map_bug](https://user-images.githubusercontent.com/57997077/83338316-47654c00-a291-11ea-98ab-298350380ae0.png)

**Comment by FreeTrade** [comment]
Thanks, could you tell me the steps to reproduce?

**Comment by 2qx** [comment]
1. From the map page, starting in London, or the user's current location
2. Pan westward until reaching a location beyond 180 longitude
3. Create a map post, 
4. On refresh, it will be found at the same latitude but displayed at 180 degrees longitude.

For example, panning left to a point near Wellington NZ, enter a point on the peak of Makara Hill.

This makes a GET requests to:
https://memberjs.org:8123/member.js?action=map&address=1M7CNxc5ZvD3BSkRpn7Q1dCmKVF76Xy31D&north=-41.28743692901678&east=-185.28832912445068&south=-41.29133063429767&west=-185.2943801879883

And submits the raw transaction:
https://memberjs.org:8123/v2/rawtransactions/sendRawTransaction/02000000016b0ca03b1a63c715d487ed052772e4070eb2381bcf9139e878d3a52ee69ae0be010000006b483045022100ded4213ea220458623cc4814fd98cb272209a8a47ea6005405979cafeef19cdb02205dcb34e59296ac48205c820e07d3177ae101414e34ab021335662e4af2721b7141210245c70df106686d00ae941395fbf4d6d98cc6f334cea91c4edcb3d8c42d069f6bffffffff020000000000000000356a026da80c3230386a30353270383530702354686973206973206d616b6172612068696c6c206e6561722077656c6c696e67746f6e4e250000000000001976a914dc8e8283af36f854976dde06116b82b85fb94fce88ac00000000

https://memberapp.github.io/#map?geohash=208j052p8520&post=74a56bd494ddd86084863551cb8720bb08812846c0d1ef6ddba06a354b311a80

![Screenshot_2020-05-31_10-05-59](https://user-images.githubusercontent.com/57997077/83354573-8e9e1c00-a327-11ea-9788-58231e16da88.png)

This was done in Chromium 73 but I have also observed it on mobile chrome browsers.

**Comment by FreeTrade** [comment]
Ok, should be fixed - the posting function will check for lon values outside of 0,180 and correct them.
