### ISSUE TITLE
Support for identicon's and user profile pictures. 

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#310]

**Comment by FreeTrade** [comment]
identicons could be done client side quite easily, the user profile pics need a serverside feature 

https://github.com/memberapp/server/issues/18

**Comment by Real-FEELS** [comment]
Any visuals would really help so if user profile pics needs to be different in favour of identicons then so be it. 

When implementing the identicons please use color version, not the standard grey ones memo uses.

**Comment by FreeTrade** [comment]
Ok, added to v4.1 -
just in dev version atm
-
https://freetrade.github.io/memberdev

**Comment by Real-FEELS** [comment]
Thanks. Could you also add it at the top of the following pages , `#member` and `#settings `pages

**Comment by FreeTrade** [comment]
> 
> 
> Thanks. Could you also add it at the top of the following pages , `#member` and `#settings `pages

OK - added for v4.2.1
