### ISSUE TITLE
Text not appearing with imgur link in post 

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#311]
Post on Memo: https://memo.cash/a/b24a6082a8
Post on Member: https://member.cash/?b24a#thread?post=b24a6082a8

For some reason the post text is discarded.

**Comment by FreeTrade** [comment]
Thank you, yes confirmed, I'd guess it is the regex that finds the imgur link is too broad although I haven't looked into it yet.

**Comment by FreeTrade** [comment]
yes, it was the regex collapsing multiple links into one, should be fixed as of 4.0.12
