### ISSUE TITLE
thread comment votes displaying NaN

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#312]
<img width="397" alt="Screenshot 2020-08-11 at 09 41 42" src="https://user-images.githubusercontent.com/68990054/89876735-fa69f400-dbb6-11ea-8540-64cdbcfc7c12.png">

span class `betweenvotesscore`

**Comment by FreeTrade** [comment]
thanks for reporting the problem, should be fixed as of 4.0.12
