### ISSUE TITLE
Add notifications on progressive web app if possible

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#314]

**Comment by FreeTrade** [comment]
May need to shift website to same server as backend

**Comment by FreeTrade** [comment]
https://member.cash/?bef4#thread?post=bef4a7ad4d

**Comment by FreeTrade** [comment]
@2qx website and backend now on same server. Have any experience with notifications in PWAs?

**Comment by 2qx** [comment]
I read about doing this a while ago.  I can do this on the 20th.  

For simplicity, we can assume that notifications will behave identical to the way they do now, and just allow for optional push notifications, which should be a separate configurable option?

**Comment by FreeTrade** [comment]
Sounds good. I've got plans to add notifications of more events too, like for replies in threads in which you've commented, maybe in topics you're subscribed to.

**Comment by FreeTrade** [comment]
@2qx - hey, did you get a chance to look at this on the 20th?

**Comment by 2qx** [comment]
Hey @FreeTrade, was a little behind last week, let me take a look now.

**Comment by 2qx** [comment]
@FreeTrade is it possible to run the server off of a `--fastsync --pruned` bchd node? I keep getting a 

```
Wait 0 seconds
Processing Block Into SQL:525471
{ code: -5, message: 'Block not found' }
```

when I try to run the server.  I may need to set up a separate computer to really get started on this.

**Comment by FreeTrade** [comment]
I think the fastsync probably takes you past the first memo transactions, so you wouldn't be able to fully sync.

A few points though - 
1. you probably don't need the full history if you're just setting it up for testing.
set config.startBlock = 651132;

2. i haven't updated the server repo for a while - so it's got an out of date version.

maybe an alternative would be just use a webserver for the member client files and use a redirect/proxy to re-route a call to get the new notification count to member.cash? or return random or dummy variables.

**Comment by FreeTrade** [comment]
@2qx Any progress on this? I've promised this as part of the six week flipstarter package, so if you don't have time for it, let me know and I'll roll up my sleeves and get it sorted.

**Comment by 2qx** [comment]
Sorry @FreeTrade , but I not sure I'm going to have the bandwidth for this.

It might be faster for you to tackle given your experience with the server code.
