### ISSUE TITLE
Vue or Nuxt support?

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#317]
Would you ever consider switching the core to a  Vue or Nuxt SPA? It would make the project more modular and easier for other dev's to join in and submit PR's

**Comment by FreeTrade** [comment]
I don't know a lot about Vue or Nuxt SPA. I do know that Vue has a really nice markup editor that read.cash uses, and I'd like to include that. I'm hesitant to switch wholesale to any framework though. I do think it limits contributions to those who are familiar with that framework and imposes a structure that is not always helpful.
