### ISSUE TITLE
Change window location on url change 

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#318]
_Given_ I am on the feed page
_When_ I scroll down and select reply link on a post further down the page
_Then_ I am taken to the post page

In the above scenario the user is left at the middle of the page. When the user is taken to another location of the site the window should be reset to the top via JS

**Comment by FreeTrade** [comment]
Thanks. I wasn't able to reproduce this though - what platform/browser are you seeing this on?

**Comment by Real-FEELS** [comment]
Chrome on MacOS. I think it apples only to my theme, perhaps because of the sticky header?

**Comment by FreeTrade** [comment]
Maybe, I'll take a look at it if it's still present when integrating the theme.
