### ISSUE TITLE
Vavilon translations for tooltips

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#323]
@2qx Not sure if it is possible to use Vavilon to do translations for tooltips, for icons for example, where html is of the form,

```
<a id="myfeedbutton" title="My Feed (Latest posts from your topics or peeps)"
                                    class="btn" href="#myfeed" onclick="showMyFeed();">📰</a>
```

**Comment by 2qx** [comment]
These labels are also important for screen readers and accessibility.  

I think there is probably some logic in Vavilon that will look for if an element has `data-vavilon`, so we could use a tag like `title-vavilon` and iterate over them separately.  

I'm a little under a deadline at the moment, but it should fairly quick to do.  

BTW, there is a v2 in the works: https://github.com/vavilon-js/vavilon.js/pull/23  It might be better to request it there so we can get back on the main branch.

**Comment by FreeTrade** [comment]
ok. I'll start adding something like data-title-vavilon to these so we can test it out later.
