### ISSUE TITLE
Add notification count to page title. 

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#370]
Add a notification count into the page title like facebook does 

<img width="241" alt="Screenshot 2020-09-06 at 13 47 10" src="https://user-images.githubusercontent.com/68990054/92326098-7b49cd80-f047-11ea-95f4-006ec65433e3.png">

**Comment by FreeTrade** [comment]
added in next update

**Comment by Real-FEELS** [comment]
Looking good - such a simple tweak but great for UX 

Although the count should be updated when the user has visited the notifications/ message. 

![Screenshot 2020-09-08 at 15 01 29](https://user-images.githubusercontent.com/68990054/92486882-81c17c00-f1e4-11ea-8efd-e3a42b2ee8d4.png)
