### ISSUE TITLE
Member cards on username hover

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#382]
<img width="392" alt="Screenshot 2020-09-10 at 18 22 52" src="https://user-images.githubusercontent.com/68990054/92771343-b7a46300-f392-11ea-9826-d18b113c66ed.png">
<img width="389" alt="Screenshot 2020-09-10 at 18 23 07" src="https://user-images.githubusercontent.com/68990054/92771345-b83cf980-f392-11ea-9f9b-b8c86dc96b1c.png">

**Comment by FreeTrade** [comment]
some more discussion - 
https://github.com/memberapp/memberapp.github.io/issues/28
