### ISSUE TITLE
Possible 304 cached content being returned when fresh calls to the db should be taking place

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#413]

**Comment by 2qx** [comment]
Is this a server side issue or client side?

**Comment by FreeTrade** [comment]
looks client side to me right now. i'm adding a time to the client requests, and a no-cache header on the server side. hopefully this fixes things up.

**Comment by FreeTrade** [comment]
Should be fixed as at 4.4.10.
