### ISSUE TITLE
users can only see messages sent to them but not the messages they sent. makes it confusing to know if you replied already or not. 

### ISSUE THREAD

**Issue by theamazingnuggets** [memberapp/memberapp.github.io#428]

**Comment by FreeTrade** [comment]
Should be possible to add sent receipts quite easily, but won't be able to show full messages that were sent.

**Comment by theamazingnuggets** [comment]
That's helpful! I just need a mark that I already replied to someone, I still like the idea that the website doesn't save much of my information. I feel secured.

**Comment by Real-FEELS** [comment]
@FreeTrade You could also store sent messages in the local-storage
