### ISSUE TITLE
jdenticons could be hidden now that profile pics are present

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#441]

**Comment by Real-FEELS** [comment]
Might it be worth creating a module with some props eg `large`, `medium`, `small` for the image/identicon, then that can be inserted anywhere it's needed. So that more DRY code can be written.

**Comment by FreeTrade** [comment]
not following you here - can you expand a bit?

**Comment by Real-FEELS** [comment]
Sorry I mean a component not a module.
