### ISSUE TITLE
Member brand nav fix 

### ISSUE THREAD

**Issue by Real-FEELS** [memberapp/memberapp.github.io#477]
<img width="288" alt="Screenshot 2020-10-07 at 08 18 49" src="https://user-images.githubusercontent.com/68990054/95299588-df91c400-0875-11eb-9d6c-43f4907d5bc7.png">
Please wrap these two span's in a div with a class called `band`

**Comment by FreeTrade** [comment]
Hmm, these is no longer any membertext near the logo

**Comment by FreeTrade** [comment]
@Real-FEELS do you still need anything done here?
