### ISSUE TITLE
Margin/padding problems 

### ISSUE THREAD

**Issue by ghost** [memberapp/memberapp.github.io#52]
I have noticed that there are some padding and margin problems on the site. On the frontpage the github version differs from the normal hacker news one.  Also on the settings page I think you need to add some padding. If I can understand how it generate the CSS on the pages maybe I can fix it.

**Comment by FreeTrade** [comment]
Sure, the CSS is all in .css files - making changes there should alter padding and spacing

**Comment by ghost** [comment]
I did some smaller changes for the spacing, will do more work later on!
