### ISSUE TITLE
One Click Tipping - user should be able to specify an amount

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#54]
When the user clicks an up arrow, default of 0 is sent as a tip - should be possible for user to be able to define this amount

**Comment by JettScythe** [comment]
Might be worthwhile to reopen this as referenced:  https://github.com/memberapp/server/issues/5#issuecomment-566858441
Allow user to allow one click tipping in single satoshi increments or custom values starting at 547 sats all the way up to their max balance.

**Comment by FreeTrade** [comment]
Ok, i'm removing the 'step' attribute.
