### ISSUE TITLE
Some wallet All operations cannot be performed ！even if it's just a name

### ISSUE THREAD

**Issue by chinaOB** [memberapp/memberapp.github.io#627]
It's not about the length of the Profile name。All operations cannot be performed ！Send Funds  , tweet ... nothing！
I believe this is not a common problem and may be related to my wallet. My wallet has received many mining payments！
Check, please. Thanks!

log：
1 Transaction(s) Still Queued, Try changing UTXO server on settings page. Retry in (seconds) 3
269 utxo(s) received. usable 269
true 200 OK errorTransactiontoobigforthisserver.Trymakingsomesmallertransactionstogroupyourutxos.
Setting Name
progress: 2 bytes transferred
loading https://member.cash/v2/member.js?action=settings&address=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&qaddress=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&r=7584
269 utxo(s) received. usable 269
QT: 1/3
progress: 60188 bytes transferred
progress: 32281 bytes transferred
progress: 92 bytes transferred
progress: 2 bytes transferred
progress: 2 bytes transferred
loading https://member.cash/v2/member.js?action=show&shownoname=false&shownopic=true&order=hot&content=posts&topicname=&filter=everyone&address=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&qaddress=&start=0&limit=25&network=3&r=4376
loading https://member.cash/v2/member.js?action=alertcount&address=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&since=1663088158&sincepm=1663088423&r=4374
loading https://member.cash/v2/regk/13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q?a=100&r=4369
loading https://member.cash/v2/member.js?action=settings&address=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&qaddress=13oGJLwXzvQF5zZEuYc41Evzd1YsPc2R1Q&r=4367

**Comment by FreeTrade** [comment]
Looks like your transaction was too big for the server. I've increased the size limit on that - give it another try, let me know how it goes.

**Comment by chinaOB** [comment]
Great! It worked!
