### ISSUE TITLE
Brave/Edge don't work from local file system

### ISSUE THREAD

**Issue by FreeTrade** [memberapp/memberapp.github.io#69]
Seem to work ok when browsing online, but some problem relate to localstorage on edge, and unspecified error on brave.

**Comment by ghost** [comment]
On Brave it gives:

> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document. at init

This is because Brave doesn't allow local files. One way to go around it is to go to Settings -> Shields  and then choose "Allow all cookies".

Havent checked out Edge, but might be a similar problem?

**Comment by FreeTrade** [comment]
Could be. It'll only be noticeable for developers at the moment, but when we launch the app, we'll have to build a basic html webserver into the backend, or recommend against using Brave.
